# Generated by Django 5.0.4 on 2024-05-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assinatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
